openapi: 3.0.3
info:
  title: Residency status for relief at source
  version: '2.0'
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
paths:
  /individuals/relief-at-source/residency-status:
    post:
      summary: Check if an individual is a Scotland, Wales or rest of the UK resident
      description: |
        Pension Scheme Administrators can find out if a pension scheme member pays tax in Scotland, Wales or in the rest of the UK. They can apply the correct rate of Income Tax to their relief at source contributions.
        From 1 January to 5 April, the API will return currentYearResidencyStatus and nextYearForecastResidencyStatus.
        From 6 April to 31 December, the API will only return currentYearResidencyStatus.
      operationId: checkIndividualResidency
      parameters:
        - name: Accept
          in: header
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          style: simple
          schema:
            type: string
            enum:
              - application/vnd.hmrc.2.0+json
          required: true
        - name: Content-Type
          in: header
          description: Specifies the format of the request body, which must be JSON.
          style: simple
          schema:
            type: string
            enum:
              - application/json
          required: true
        - name: Authorization
          in: header
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints) with the `read:ras` scope.
          style: simple
          schema:
            type: string
            example: Bearer bb7fed3fe10dd235a2ccda3d50fb
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: Residency status request
                  required:
                    - nino
                    - firstName
                    - lastName
                    - dateOfBirth
                  type: object
                  properties:
                    nino:
                      pattern: ^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]$
                      type: string
                      description: The pension scheme member’s National Insurance number.
                      example: BB123456B
                    firstName:
                      pattern: ^[a-zA-Z &`\-\'^]{1,35}$
                      type: string
                      description: The pension scheme member’s first name.
                      example: John
                    lastName:
                      pattern: ^[a-zA-Z &`\-\'^]{1,35}$
                      type: string
                      description: The pension scheme member’s last name.
                      example: Smith
                    dateOfBirth:
                      pattern: ^\d{4}-\d{2}-\d{2}$
                      type: string
                      description: The pension scheme member’s date of birth. This cannot be in the future.
                      example: '1975-05-25'
            example:
              nino: BB123456B
              firstName: John
              lastName: Smith
              dateOfBirth: '1975-05-25'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - title: Relief at source residency status response
                    required: &ref_3
                      - currentYearResidencyStatus
                    type: object
                    properties: &ref_4
                      currentYearResidencyStatus:
                        title: UK residency status type
                        enum: &ref_0
                          - scotResident
                          - welshResident
                          - otherUKResident
                        type: string
                      nextYearForecastResidencyStatus:
                        title: UK residency status type
                        enum: *ref_0
                        type: string
              example:
                currentYearResidencyStatus: otherUKResident
                nextYearForecastResidencyStatus: scotResident
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - title: Error response
                    required: &ref_1
                      - code
                      - message
                    type: object
                    properties: &ref_2
                      code:
                        title: Error code type
                        enum:
                          - BAD_REQUEST
                          - STATUS_UNAVAILABLE
                        type: string
                      message:
                        type: string
              example:
                code: BAD_REQUEST
                message: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                allOf:
                  - title: Error response
                    required: *ref_1
                    type: object
                    properties: *ref_2
                  - description: The pension scheme member's details do not match with HMRC's records.
              example:
                code: STATUS_UNAVAILABLE
                message: Cannot provide a residency status for this pension scheme member.
      deprecated: false
      security:
        - user-restricted:
            - read:ras
components:
  securitySchemes:
    user-restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token in the Authorization header.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:ras: Access to Relief At Source API's
  schemas:
    residencyStatusResponse:
      title: Relief at source residency status response
      required: *ref_3
      type: object
      properties: *ref_4
    errorResponse:
      title: Error response
      required: *ref_1
      type: object
      properties: *ref_2
