openapi: 3.0.3
info:
  title: Residency status for relief at source
  version: "1.0"
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
paths:
  /individuals/relief-at-source/residency-status:
    post:
      summary: Check if an individual is a Scottish resident
      description: |
        Find out if a scheme member pays tax in Scotland or in the rest of the UK, to tell you the rate of tax to use for their relief at source contributions.
        From 1 January to 5 April each year you will get currentYearResidencyStatus and nextYearForecastResidencyStatus within the response json.
        From 6 April to 31 December each year you will only get currentYearResidencyStatus within the response json.
      operationId: checkIndividualResidency
      parameters:
      - name: Accept
        in: header
        description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
          \ of the API to be used."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/vnd.hmrc.1.0+json
      - name: Content-Type
        in: header
        description: "Specifies the format of the request body, which must be JSON."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/json
      - name: Authorization
        in: header
        description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints)\
          \ with the `read:ras` scope."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      requestBody:
        content:
          application/json:
            schema:
              required:
              - dateOfBirth
              - firstName
              - lastName
              - nino
              type: object
              properties:
                nino:
                  pattern: "^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]$"
                  type: string
                  description: The pension scheme member’s National Insurance number.
                  example: BB123456B
                firstName:
                  pattern: "^[a-zA-Z &`\\-\\'^]{1,35}$"
                  type: string
                  description: The pension scheme member’s first name.
                  example: John
                lastName:
                  pattern: "^[a-zA-Z &`\\-\\'^]{1,35}$"
                  type: string
                  description: The pension scheme member’s last name.
                  example: Smith
                dateOfBirth:
                  pattern: "^\\d{4}-\\d{2}-\\d{2}$"
                  type: string
                  description: The pension scheme member’s date of birth. This cannot
                    be in the future.
                  example: 1975-05-25
            example:
              nino: BB123456B
              firstName: John
              lastName: Smith
              dateOfBirth: 1975-05-25
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                required:
                - currentYearResidencyStatus
                type: object
                properties:
                  currentYearResidencyStatus:
                    title: UK residency status type
                    type: string
                    enum:
                    - scotResident
                    - otherUKResident
                  nextYearForecastResidencyStatus:
                    title: UK residency status type
                    type: string
                    enum:
                    - scotResident
                    - otherUKResident
              example:
                currentYearResidencyStatus: otherUKResident
                nextYearForecastResidencyStatus: scotResident
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - code
                - message
                type: object
                properties:
                  code:
                    title: Error code type
                    type: string
                    enum:
                    - BAD_REQUEST
                    - STATUS_UNAVAILABLE
                  message:
                    type: string
              example:
                code: BAD_REQUEST
                message: Bad Request
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                required:
                - code
                - message
                type: object
                properties:
                  code:
                    title: Error code type
                    type: string
                    enum:
                    - BAD_REQUEST
                    - STATUS_UNAVAILABLE
                  message:
                    type: string
                description: The pension scheme member's details do not match with
                  HMRC's records.
              example:
                code: STATUS_UNAVAILABLE
                message: Cannot provide a residency status for this pension scheme
                  member.
      deprecated: false
      security:
      - user-restricted:
        - read:ras
components:
  schemas:
    residencyStatusRequest:
      title: Residency status request
      required:
      - dateOfBirth
      - firstName
      - lastName
      - nino
      type: object
      properties:
        nino:
          pattern: "^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]$"
          type: string
          description: The pension scheme member’s National Insurance number.
          example: BB123456B
        firstName:
          pattern: "^[a-zA-Z &`\\-\\'^]{1,35}$"
          type: string
          description: The pension scheme member’s first name.
          example: John
        lastName:
          pattern: "^[a-zA-Z &`\\-\\'^]{1,35}$"
          type: string
          description: The pension scheme member’s last name.
          example: Smith
        dateOfBirth:
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          type: string
          description: The pension scheme member’s date of birth. This cannot be in
            the future.
          example: 1975-05-25
    residencyStatusResponse:
      title: Relief at source residency status response
      required:
      - currentYearResidencyStatus
      type: object
      properties:
        currentYearResidencyStatus:
          title: UK residency status type
          type: string
          enum:
          - scotResident
          - otherUKResident
        nextYearForecastResidencyStatus:
          title: UK residency status type
          type: string
          enum:
          - scotResident
          - otherUKResident
    UKResidencyStatusType:
      title: UK residency status type
      type: string
      enum:
      - scotResident
      - otherUKResident
    error-codeType:
      title: Error code type
      type: string
      enum:
      - BAD_REQUEST
      - STATUS_UNAVAILABLE
    errorResponse:
      title: Error response
      required:
      - code
      - message
      type: object
      properties:
        code:
          title: Error code type
          type: string
          enum:
          - BAD_REQUEST
          - STATUS_UNAVAILABLE
        message:
          type: string
  parameters:
    acceptHeader:
      name: Accept
      in: header
      description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
        \ of the API to be used."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/vnd.hmrc.1.0+json
    contentTypeHeader:
      name: Content-Type
      in: header
      description: "Specifies the format of the request body, which must be JSON."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/json
    authorizationHeader:
      name: Authorization
      in: header
      description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ with the `read:ras` scope."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  securitySchemes:
    user-restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ API requests using an OAuth 2.0 Bearer Token in the Authorization header."
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:ras: Access to Relief At Source API's
